name: Prerelease

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get next Version
      id: tag_version
      uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: .*
        dry_run: true

    - uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Build jar with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' jar distZip

    - name: Publish to GitHub Maven with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' publishGeowerkstattTestbedRunnerPublicationToGitHubPackagesRepository
      env:
        ORG_GRADLE_PROJECT_GITHUB_ACTOR: ${{ github.actor }}
        ORG_GRADLE_PROJECT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    - name: Publish to OSSRH Maven with Gradle
      run: ./gradlew -Pversion='${{ steps.tag_version.outputs.new_version }}-SNAPSHOT' publishToSonatype
      env:
        ORG_GRADLE_PROJECT_OSSRH_USER: ${{ secrets.OSSRH_USER }}
        ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

    - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
      with:
        artifacts: "build/libs/*.jar,build/distributions/*.zip"
        allowUpdates: true
        name: ${{ steps.tag_version.outputs.new_tag }}-SNAPSHOT
        tag: ${{ steps.tag_version.outputs.new_tag }}-SNAPSHOT-${{ github.run_id }}
        commit: ${{ github.sha }}
        body: ${{ steps.tag_version.outputs.changelog }}
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
